import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/custom/navbar/NavBar";
import { QueryProvider } from "@/lib/React-query-setup";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "core-js/stable";

import "regenerator-runtime/runtime";
import { Suspense } from "react";
import ClientSideScrollRestorer from "@/components/ui/custom/common/ClientSideScrollRestorer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-palette-bg h-full`}
      >
        <ClientSideScrollRestorer />
        <QueryProvider>
          <NuqsAdapter>
            <Navbar />

            {children}
            <Toaster />
          </NuqsAdapter>
        </QueryProvider>
      </body>
    </html>
  );
}
